---
# Base task for configuring a Raspi

- name: 'Transfer init scripts'
  become: yes
  become_method: sudo
  copy: src=./ dest=/home/pi/init/ mode=0755

- name: 'Thin out Raspbian'
  become: yes
  become_method: sudo
  shell: /home/pi/init/anti-raspbian-bloat.sh

#downloading key and installing mosquitto
- name: 'Download and add moquitto-reqpo-key'
  become: yes
  become_method: sudo
  apt_key:
    url: http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
    state: present

- name: 'Download repo list'
  become: yes
  become_method: sudo
  get_url:
      url: http://repo.mosquitto.org/debian/mosquitto-jessie.list
      dest: /etc/apt/sources.list.d/

- apt: update_cache=yes
  name: 'Update apt cache'
  become: yes
  become_method: sudo

- apt: upgrade=dist
  name: 'Upgrade apt dist'
  become: yes
  become_method: sudo

- name: 'Configure locale'
  become: yes
  become_method: sudo
  shell: /home/pi/init/configure-locale.sh

- name: 'Set timezone'
  become: yes
  become_method: sudo
  shell: /home/pi/init/set-timezone.sh

- name: 'Set keyboard layout'
  become: yes
  become_method: sudo
  shell: /home/pi/init/set-keyboard-layout.sh

- name: 'Install packages'
  apt:
    name={{item}}
    state=installed
  become: yes
  become_method: sudo
  with_items:
    - git 
    - python3 
    - python3-pip 
    - python3-venv
    - libnl-3-dev
    - libnl-genl-3-dev
    - cmake
    - make
    - g++
    - mosquitto
    - mosquitto-clients
    - libmosquitto-dev
    - libmosquittopp-dev
    - libssl-dev
    - jq

- name: 'Get git repositories'
  become: yes
  become_user: pi
  git: 
    repo: https://github.com/linusmotu/random_pi_forest.git 
    version: WIP 
    dest: /home/pi/git/random_pi_forest

- name: 'Get sockets repo'
  become: yes
  become_user: pi
  git: 
    repo: https://github.com/linusmotu/flask_socketsio.git 
    version: master 
    dest: /home/pi/git/flask_socketsio

- name: 'Get batctl repo'
  become: yes
  become_user: pi
  git: 
    repo: https://git.open-mesh.org/batctl.git 
    version: master 
    dest: /home/pi/git/batctl

# Make install batcl after git clone
- make:
    chdir: /home/pi/git/batctl
    target: install
  become: yes
  become_method: sudo

# Setup mesh on the node
- name: 'Get mesh IP'
  set_fact:
    contents={{ lookup('file', '../../../mesh_ip.txt') }}
    
- name: 'Setup mesh network'
  command: "sh /home/pi/git/random_pi_forest/scripts/manscript.sh force {{contents}}"

# I don't see the use of the previous steps now (for mesh)
- name: 'Update bashrc so do manscript on reboot.'
  lineinfile:
      path: /home/pi/.bashrc
      line: '/home/pi/git/random_pi_forest/scripts/manscript.sh 0 {{contents}}'

- name: 'Reboot'
  become: yes
  become_method: sudo
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
